

...............................
Start: sql 
In:     C:\xampp\htdocs\cloudfin_bee\bee\hive.php 
On:    60
...............................
string(322) "SELECT hive.id as hives__id, hive.name as hives__name, hive.hive_name as hives__hive_name, hive.email as hives__email, hive.phone_number as hives__phone_number, hive.country as hives__country, hive.code as hives__code, hive.status as hives__status, hive.password as hives__password FROM hive   WHERE  (hive.is_deleted = 0)"

...............................
End: sql 
...............................



...............................
Start: sql 
In:     C:\xampp\htdocs\cloudfin_bee\bee\hive.php 
On:    60
...............................
string(215) "SELECT comb.id as combs__id, comb.hive_id as combs__hive_id, comb.name as combs__name, comb.description as combs__description FROM comb   WHERE  (comb.is_deleted = 0) AND (( comb.hive_id = 1) OR ( comb.hive_id = 2))"

...............................
End: sql 
...............................



...............................
Start: sql 
In:     C:\xampp\htdocs\cloudfin_bee\bee\hive.php 
On:    60
...............................
string(220) "SELECT section.id as sections__id, section.comb_id as sections__comb_id, section.name as sections__name, section.db_kind as sections__db_kind, section.type as sections__type FROM section   WHERE  (section.is_deleted = 0)"

...............................
End: sql 
...............................



...............................
Start: sql 
In:     C:\xampp\htdocs\cloudfin_bee\bee\hive.php 
On:    60
...............................
string(312) "SELECT section_fragile.id as section_fragiles__id, section_fragile.section_id as section_fragiles__section_id, section_fragile.section_name as section_fragiles__section_name, section_fragile.used_by_section_id as section_fragiles__used_by_section_id FROM section_fragile   WHERE  (section_fragile.is_deleted = 0)"

...............................
End: sql 
...............................



...............................
Start: sql 
In:     C:\xampp\htdocs\cloudfin_bee\bee\hive.php 
On:    60
...............................
string(379) "SELECT module.id as modules__id, module.hive_id as modules__hive_id, module.time_to_expire as modules__time_to_expire, module.code as modules__code, module.hive_name as modules__hive_name, module.cost as modules__cost, module.paid as modules__paid, module.status as modules__status FROM module   WHERE  (module.is_deleted = 0) AND (( module.hive_id = 1) OR ( module.hive_id = 2))"

...............................
End: sql 
...............................



...............................
Start: sql 
In:     C:\xampp\htdocs\cloudfin_bee\bee\hive.php 
On:    60
...............................
string(359) "SELECT hive_user.id as hive_users__id, hive_user.user_id as hive_users__user_id, hive_user.hive_id as hive_users__hive_id, hive_user.hive_name as hive_users__hive_name, hive_user.email as hive_users__email, hive_user.password as hive_users__password FROM hive_user   WHERE  (hive_user.is_deleted = 0) AND (( hive_user.hive_id = 1) OR ( hive_user.hive_id = 2))"

...............................
End: sql 
...............................



...............................
Start: sql 
In:     C:\xampp\htdocs\cloudfin_bee\bee\hive.php 
On:    60
...............................
string(330) "SELECT user.id as users__id, user.name as users__name, user.email as users__email, user.tenant_of as users__tenant_of, user.is_owner as users__is_owner, user.password as users__password, user.status as users__status, user.code as users__code, user.avatar as users__avatar FROM user   WHERE  (user.is_deleted = 0) AND (user.id = 1)"

...............................
End: sql 
...............................



...............................
Start: sql 
In:     C:\xampp\htdocs\cloudfin_bee\bee\hive.php 
On:    60
...............................
string(409) "SELECT user_role.id as user_roles__id, user_role.user_id as user_roles__user_id, user_role.role_id as user_roles__role_id, user_role.status as user_roles__status,   role.id as user_roles__role__id, role.name as user_roles__role__name, role.description as user_roles__role__description FROM user_role  INNER JOIN role ON user_role.role_id=role.id   WHERE  (user_role.is_deleted = 0) AND (user_role.user_id = 1)"

...............................
End: sql 
...............................



...............................
Start: sql 
In:     C:\xampp\htdocs\cloudfin_bee\bee\hive.php 
On:    60
...............................
string(533) "SELECT role_permisiion.id as role_permisiions__id, role_permisiion.role_id as role_permisiions__role_id, role_permisiion.permission as role_permisiions__permission, role_permisiion.can_create as role_permisiions__can_create, role_permisiion.can_read as role_permisiions__can_read, role_permisiion.can_update as role_permisiions__can_update, role_permisiion.can_delete as role_permisiions__can_delete FROM role_permisiion   WHERE  (role_permisiion.is_deleted = 0) AND (( role_permisiion.role_id = 1) OR ( role_permisiion.role_id = 2))"

...............................
End: sql 
...............................



...............................
Start: sql 
In:     C:\xampp\htdocs\cloudfin_bee\bee\hive.php 
On:    60
...............................
string(303) "SELECT role_module.id as role_modules__id, role_module.role_id as role_modules__role_id, role_module.module_code as role_modules__module_code, role_module.status as role_modules__status FROM role_module   WHERE  (role_module.is_deleted = 0) AND (( role_module.role_id = 1) OR ( role_module.role_id = 2))"

...............................
End: sql 
...............................



...............................
Start: sql 
In:     C:\xampp\htdocs\cloudfin_bee\bee\hive.php 
On:    60
...............................
string(533) "SELECT role_permisiion.id as role_permisiions__id, role_permisiion.role_id as role_permisiions__role_id, role_permisiion.permission as role_permisiions__permission, role_permisiion.can_create as role_permisiions__can_create, role_permisiion.can_read as role_permisiions__can_read, role_permisiion.can_update as role_permisiions__can_update, role_permisiion.can_delete as role_permisiions__can_delete FROM role_permisiion   WHERE  (role_permisiion.is_deleted = 0) AND (( role_permisiion.role_id = 1) OR ( role_permisiion.role_id = 2))"

...............................
End: sql 
...............................



...............................
Start: sql 
In:     C:\xampp\htdocs\cloudfin_bee\bee\hive.php 
On:    60
...............................
string(303) "SELECT role_module.id as role_modules__id, role_module.role_id as role_modules__role_id, role_module.module_code as role_modules__module_code, role_module.status as role_modules__status FROM role_module   WHERE  (role_module.is_deleted = 0) AND (( role_module.role_id = 1) OR ( role_module.role_id = 2))"

...............................
End: sql 
...............................

groupby: accounting_transaction.occurancy_date, 

...............................
Start: sql 
In:     C:\xampp\htdocs\cloudfin_bee\bee\hive.php 
On:    60
...............................
string(2047) "SELECT accounting_transaction.id as accounting_transactions__id, accounting_transaction.accounting_event_id as accounting_transactions__accounting_event_id, accounting_transaction.journal_id as accounting_transactions__journal_id, accounting_transaction.occurancy_time as accounting_transactions__occurancy_time, accounting_transaction.occurancy_date as accounting_transactions__occurancy_date, accounting_transaction.amount as accounting_transactions__amount, accounting_transaction.direction as accounting_transactions__direction, accounting_transaction.fiscal_year_id as accounting_transactions__fiscal_year_id, accounting_transaction.description as accounting_transactions__description, accounting_transaction.user_id as accounting_transactions__user_id, accounting_transaction.is_closed as accounting_transactions__is_closed, accounting_transaction.is_manuall_entry as accounting_transactions__is_manuall_entry, accounting_transaction.accounting_closure_id as accounting_transactions__accounting_closure_id, accounting_transaction.remarks as accounting_transactions__remarks,   accounting_event.id as accounting_transactions__accounting_event__id, accounting_event.name as accounting_transactions__accounting_event__name, accounting_event.code as accounting_transactions__accounting_event__code, accounting_event.sort_order as accounting_transactions__accounting_event__sort_order, accounting_event.system_event_name as accounting_transactions__accounting_event__system_event_name,   journal.id as accounting_transactions__journal__id, journal.name as accounting_transactions__journal__name, journal.description as accounting_transactions__journal__description FROM accounting_transaction  INNER JOIN accounting_event ON accounting_transaction.accounting_event_id=accounting_event.id  INNER JOIN journal ON accounting_transaction.journal_id=journal.id   WHERE  (accounting_transaction.is_deleted = 0) AND (accounting_transaction.is_closed = 0) GROUP BY accounting_transaction.occurancy_date ORDER BY accounting_transaction.occurancy_time DESC"

...............................
End: sql 
...............................

{"accounting_transactions":[{"id":5,"accounting_event_id":"2","journal_id":"1","occurancy_time":1553472000,"occurancy_date":"2019-03-25","amount":700000,"direction":"debit","fiscal_year_id":"1","description":"testing","user_id":"1","is_closed":0,"is_manuall_entry":1,"accounting_closure_id":"0","remarks":"Manual Entry","accounting_event":{"id":2,"name":"Loan Provision","code":"LLP","sort_order":2,"system_event_name":"Loan Disbursment"},"journal":{"id":1,"name":"ugx","description":"ugx journal"}},{"id":1,"accounting_event_id":"1","journal_id":"1","occurancy_time":1553212800,"occurancy_date":"2019-03-22","amount":45000,"direction":"debit","fiscal_year_id":"1","description":"this sb test","user_id":"1","is_closed":0,"is_manuall_entry":1,"accounting_closure_id":"0","remarks":"Manual Entry","accounting_event":{"id":1,"name":"Disbursment Of Loan Amount","code":"DOLA","sort_order":1,"system_event_name":"Loan Disbursment"},"journal":{"id":1,"name":"ugx","description":"ugx journal"}},{"id":4,"accounting_event_id":"2","journal_id":"1","occurancy_time":1552521600,"occurancy_date":"2019-03-14","amount":700000,"direction":"credit","fiscal_year_id":"1","description":"desc","user_id":"1","is_closed":0,"is_manuall_entry":1,"accounting_closure_id":"0","remarks":"Manual Entry","accounting_event":{"id":2,"name":"Loan Provision","code":"LLP","sort_order":2,"system_event_name":"Loan Disbursment"},"journal":{"id":1,"name":"ugx","description":"ugx journal"}}],"_errors":[]}